version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      default-days: 7
      exclude:
        - "databricks*"
    schedule:
      interval: "daily"
    groups:
      # Patch-level updates are low-risk, and can be batched together into a single PR to reduce update noise.
      batch-patch-updates:
        update-types:
          - "patch"
