name: build

on:
  pull_request:
    types: [opened, synchronize]
  merge_group:
    types: [checks_requested]
  push:
    # Always run on push to main. The build cache can only be reused
    # if it was saved by a run from the repository's default branch.
    # The run result will be identical to that from the merge queue
    # because the commit is identical, yet we need to perform it to
    # seed the build cache.
    branches:
      - main

env:
  HATCH_VERBOSE: "2"
  HATCH_VERSION: "1.16.5"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.10', '3.11', '3.12', '3.13', '3.14' ]
    env:
      HATCH_ENV: "test.py${{ matrix.python }}"
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          # The version under test, as well as Python 3.14 for Hatch.
          python-version: |
            ${{ matrix.python }}
            ${{ matrix.python != '3.14' && '3.14' || '' }}

      - name: Install hatch
        run: pip install "hatch==${HATCH_VERSION}"

      - name: Run unit tests
        run: make test

      - name: Publish test coverage
        uses: odecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de  # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.14'

      - name: Install hatch
        run: pip install "hatch==${HATCH_VERSION}"

      - name: Reformat code
        run: make fmt

      - name: Fail on differences
        run: |
          # Exit with status code 1 if there are differences (i.e. unformatted files)
          git diff --exit-code
